// src/app/features/auth/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss'
})
export class LoginComponent {
  email = '';
  password = '';
  rememberMe = false;
  loading = false;
  errorMessage = '';

  constructor(private router: Router) {}

  onSubmit(): void {
    if (!this.email || !this.password) {
      this.errorMessage = 'Please enter both email and password.';
      return;
    }

    this.loading = true;
    this.errorMessage = '';

    // Simulate login process
    setTimeout(() => {
      this.loading = false;
      
      // For demo purposes, accept any email/password combination
      if (this.email && this.password) {
        // Simulate successful login
        alert('Login successful! (Demo mode)');
        this.router.navigate(['/home']);
      } else {
        this.errorMessage = 'Invalid credentials. Please try again.';
      }
    }, 1500);
  }

  navigateBack(): void {
    this.router.navigate(['/home']);
  }
}
<!-- Login Page -->
<div class="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  
  <!-- Header with logo -->
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
    <div class="flex justify-center">
      <img src="assets/logo.png" alt="CoST Logo" class="h-12 w-auto">
    </div>
    <h2 class="mt-6 text-center text-3xl font-bold text-cost-charcoal">
      Sign in to CoST Knowledge Hub
    </h2>
    <p class="mt-2 text-center text-sm text-gray-600">
      Access exclusive resources and tools for infrastructure transparency
    </p>
  </div>

  <!-- Login Form -->
  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow-lg sm:rounded-lg sm:px-10">
      
      <!-- Error Message -->
      <div *ngIf="errorMessage" class="mb-4 p-3 bg-red-50 border border-red-200 rounded-md">
        <p class="text-sm text-red-600">{{ errorMessage }}</p>
      </div>

      <!-- Login Form -->
      <form (ngSubmit)="onSubmit()" #loginForm="ngForm" class="space-y-6">
        
        <!-- Email Field -->
        <div>
          <label for="email" class="block text-sm font-medium text-gray-700">
            Email address
          </label>
          <div class="mt-1">
            <input
              id="email"
              name="email"
              type="email"
              [(ngModel)]="email"
              required
              autocomplete="email"
              class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:ring-cost-teal focus:border-cost-teal sm:text-sm"
              placeholder="Enter your email">
          </div>
        </div>

        <!-- Password Field -->
        <div>
          <label for="password" class="block text-sm font-medium text-gray-700">
            Password
          </label>
          <div class="mt-1">
            <input
              id="password"
              name="password"
              type="password"
              [(ngModel)]="password"
              required
              autocomplete="current-password"
              class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:ring-cost-teal focus:border-cost-teal sm:text-sm"
              placeholder="Enter your password">
          </div>
        </div>

        <!-- Remember Me -->
        <div class="flex items-center justify-between">
          <div class="flex items-center">
            <input
              id="remember-me"
              name="remember-me"
              type="checkbox"
              [(ngModel)]="rememberMe"
              class="h-4 w-4 text-cost-teal focus:ring-cost-teal border-gray-300 rounded">
            <label for="remember-me" class="ml-2 block text-sm text-gray-900">
              Remember me
            </label>
          </div>

          <div class="text-sm">
            <a href="#" class="font-medium text-cost-teal hover:text-cost-cyan">
              Forgot your password?
            </a>
          </div>
        </div>

        <!-- Submit Button -->
        <div>
          <button
            type="submit"
            [disabled]="loading || !loginForm.form.valid"
            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-cost-teal hover:bg-cost-teal/90 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cost-teal disabled:opacity-50 disabled:cursor-not-allowed transition-colors">
            
            <!-- Loading Spinner -->
            <span *ngIf="loading" class="mr-2">
              <svg class="animate-spin h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
            </span>
            
            {{ loading ? 'Signing in...' : 'Sign in' }}
          </button>
        </div>
      </form>

      <!-- Demo Notice -->
      <div class="mt-6 p-4 bg-cost-gray rounded-md">
        <div class="flex">
          <svg class="h-5 w-5 text-cost-teal" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
          </svg>
          <div class="ml-3">
            <p class="text-sm text-gray-600">
              <strong class="text-cost-teal">Demo Mode:</strong> Use any email and password to sign in and explore the platform.
            </p>
          </div>
        </div>
      </div>

      <!-- Back to Home -->
      <div class="mt-6 text-center">
        <button
          (click)="navigateBack()"
          class="text-sm text-cost-teal hover:text-cost-cyan font-medium">
          ← Back to Knowledge Hub
        </button>
      </div>

    </div>
  </div>

  <!-- Footer -->
  <div class="mt-8 text-center">
    <p class="text-xs text-gray-500">
      &copy; 2025 CoST Knowledge Hub. Leading insight for infrastructure transparency.
    </p>
  </div>

</div>

// admin/app/login/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { authApi } from '@/lib/api';
import { ErrorMessage } from '@/components/ErrorMessage';

export default function LoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      await authApi.login(email, password);
      router.push('/');
    } catch (err) {
      setError(
        err instanceof Error ? err.message : 'Login failed. Please try again.'
      );
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-cost-blue flex items-center justify-center p-4">
      <div className="w-full max-w-md bg-cost-white rounded-2xl shadow-xl p-8">
        {/* Logo */}
        <div className="flex justify-center mb-6">
          <div className="w-16 h-16 bg-cost-red rounded-2xl flex items-center justify-center text-white">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <polyline points="22 12 18 12 15 21 9 3 6 12 2 12" />
            </svg>
          </div>
        </div>

        <h1 className="text-3xl font-bold text-cost-dark mb-2 text-center">
          CoST Admin
        </h1>
        <p className="text-center text-cost-medium mb-8">
          Sign in to your account
        </p>

        {error && <ErrorMessage message={error} onDismiss={() => setError('')} />}

        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label
              htmlFor="email"
              className="block text-sm font-medium text-cost-dark mb-2"
            >
              Email
            </label>
            <input
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              className="w-full px-4 py-2 border border-cost-light/50 rounded-md focus:ring-2 focus:ring-cost-blue focus:border-transparent transition-all"
              placeholder="admin@example.com"
            />
          </div>

          <div>
            <label
              htmlFor="password"
              className="block text-sm font-medium text-cost-dark mb-2"
            >
              Password
            </label>
            <input
              id="password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              className="w-full px-4 py-2 border border-cost-light/50 rounded-md focus:ring-2 focus:ring-cost-blue focus:border-transparent transition-all"
              placeholder="••••••••"
            />
          </div>

          <button
            type="submit"
            disabled={isLoading}
            className="w-full py-3 px-4 bg-cost-red text-white font-medium rounded-md hover:bg-cost-red-600 disabled:opacity-50 transition-colors"
          >
            {isLoading ? 'Signing in...' : 'Sign In'}
          </button>
        </form>

        <div className="mt-8 pt-6 border-t border-cost-light/30">
          <p className="text-center text-sm text-cost-medium mb-3">
            Need access? Contact your CoST administrator.
          </p>
          <a
            href="https://infrastructuretransparency.org/contact/"
            target="_blank"
            rel="noopener noreferrer"
            className="block text-center text-sm text-cost-blue hover:text-cost-blue-700 font-medium transition-colors"
          >
            Request Admin Access →
          </a>
        </div>
      </div>
    </div>
  );
}
